name: test_and_merge

on:
    push:
      branches: [ staging ]
    pull_request:
      branches: [ staging ]

    workflow_dispatch:

jobs:
    unit-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Get source code from repository.
          uses: actions/checkout@v2

        - name: Install pytest.
          run: |
            python -m pip install --upgrade pip
            python -m pip install pytest pytest-xdist

        - name: Install Pandoc.
          run: |
            sudo apt install pandoc

        - name: Install markdown2man dependencies.
          run:
            python -m pip install -r requirements.txt

        - name: Run unit-tests.
          run: |
            python -m pytest
    
#    merge-testing:
#      runs-on: ubuntu-latest
#      needs: unit-tests
#      steps:
#        - name: Get source code from repository,
#          uses: actions/checkout@v2
#
#        - name: Merge staging with testing.
#          uses: devmasx/merge-branch@master
#          with:
#            type: now
#            from_branch: staging
#            target_branch: testing
#            github_token: ${{ secrets.GITHUB_TOKEN }}

    integration-tests:
      runs-on: ubuntu-latest
      needs: unit-tests
      steps:
        - name: Get source code from repository.
          uses: actions/checkout@v2

        - name: Try to use markdown2man as an action to build our test manpage.
          uses: dante-signal31/markdown2man@staging
          with:
              markdown_file: src/tests/resources/README.md
              manpage_name: cifra
              manpage_section: 1

        - name: Check that markdown actually generated a correct manpage.
          shell: bash
          run: |
            test -f src/tests/resources/cifra.1.gz || { echo "Manpage not found"; exit 1; }

    merge-master:
      runs-on: ubuntu-latest
      needs: integration-tests
      steps:
        - name: Get source code from repository.
          uses: actions/checkout@v2

        - name: Merge staging with master.
          uses: devmasx/merge-branch@master
          with:
            type: now
            from_branch: staging
            target_branch: main
            github_token: ${{ secrets.GITHUB_TOKEN }}
